local:
  host: http://localhost:3000/facilities-management
  account_username:
  account_password:
cmpdev:
  host: https://cmp.cmpdev.crowncommercial.gov.uk/facilities-management
  account_username:
  account_password:
preview:
  host: https://cmp.fm-preview.crowncommercial.gov.uk/facilities-management
  account_username:
  account_password:

